comment
segersrobbert/HackYourFuture-Javascript2 pull request #11
Opened 2019-05-04 04:09 UTC by Frisca13

I'm sorry. I tried my best. I still could not figure whyy my app.js won't run at all. 
I think, the problem is on my code. So, I deleted it but i just want to submit first. I will fix it again soon.

2019-05-05 07:14 UTC, ldealmei requested changes

2019-05-05 07:14 UTC, ldealmei commented on Week1/exercise/w1/index.js
> +  const selectImageInput = document.getElementById('imageInput');
It would be best to select these elements outside of the function call, since they do not change

2019-05-05 07:14 UTC, ldealmei commented on Week1/exercise/w1/index.js
> +  const getTodoInput = document.querySelector('#todoInput');
Here too, put querySelector calls outside of function

2019-05-11 20:13 UTC, Frisca13 commented
maartjes work

2019-07-06 11:09 UTC, closed without merging