I've done the first exercise
segersrobbert/HackYourFuture-Javascript2 pull request #2
Opened 2019-04-29 07:12 UTC by codelawer

This repo forked, and cloned via using gitbash.
The following steps had been taken in **gitbash** : 

1. - git add .; 
2. - git commit -m, 
3. - git push,

In browser send 

- [ ] pull request.

2019-04-29 19:44 UTC, bitsagarob requested changes

2019-04-29 19:44 UTC, segersrobbert commented on Week1/exercise/w1/index.js
> +  const getTodoList = document.querySelector('#todoList');
better to define these variables outside this function such that they are only selected once and not every time this function is called

2019-04-29 19:44 UTC, bitsagarob requested changes

2019-04-29 19:44 UTC, segersrobbert commented on Week1/exercise/w1/index.js
> +  const imgElement = document.querySelector('#imageToChange');
better to define these variables outside this function such that they are only selected once and not every time this function is called

2019-05-01 10:02 UTC, ldealmei requested changes
Well done for the first exercice.
For the second though, have you tested it? Does it behave as we would expect a to-do list to work?
What can you do to improve on the current behavior?
Hint: we often have to-do lists for more than one thing

2019-05-03 10:38 UTC, ldealmei commented
Exercices 1 & 2 are good :) 
Have a try for the book exercise!

2019-05-05 07:02 UTC, segersrobbert commented on Week1/homework/main.js
> +      const h2 = document.createElement("h2");
these h2, h3, h4 can have better naming. Think in what they represent, not what they are

2019-05-05 07:03 UTC, segersrobbert commented on Week1/homework/main.js
> +  newButton.style.margin = '2%';
you can set classes from you JS and set your styling in css files, separation makes it cleaner

2019-05-05 07:05 UTC, bitsagarob requested changes
good commenting but you can remove the unused old commented code, makes it cleaner

2019-07-06 11:09 UTC, closed without merging