edit Week1/homework/app.js and edit Week1/homework/index.html and add…
segersrobbert/HackYourFuture-Javascript2 pull request #7
Opened 2019-05-03 11:35 UTC by abdulsalamalmahdi

… js2_week1_class exercise/index.html and add js2_week1_class exercise/index.js

2019-05-03 11:35 UTC, abdulsalamalmahdi commented
could not figure out how to insert the object into list items

2019-05-05 07:27 UTC, segersrobbert commented on Week1/homework/app.js
> +  function idToListF (array){
try to come up with a better name, make clear what it does

2019-05-05 07:28 UTC, segersrobbert commented on js2_week1_class exercise/index.js
> +    const todoList = listNode.removeChild(listNode.getElementsByTagName('li')[0]);
try to get the list by ID

2019-05-05 07:29 UTC, segersrobbert commented on js2_week1_class exercise/index.js
> +
is there a missing } here?

2019-05-05 07:29 UTC, bitsagarob requested changes
Nice try, good job! Is this code working? there seem to be syntax error. Try to make the books exercise also

2019-07-06 11:09 UTC, closed without merging