Yousef Katat
segersrobbert/HackYourFuture-Javascript2 pull request #9
Opened 2019-05-03 19:40 UTC by yousefnk

2019-05-05 07:21 UTC, ldealmei requested changes

2019-05-05 07:21 UTC, ldealmei commented on Week1/exercise/w1/index.js
> +    const imageInput = document.getElementById("imageInput");
Select elements only once, and outside the function

2019-05-05 07:21 UTC, ldealmei commented on Week1/exercise/w1/index.js
> +    image.src = 'https://www.nieuwsbladtransport.nl/wp-content/uploads/2019/03/big-data-cyber-security-hack.jpg';
Try now, to change `image.src` to the value of the `imageInput`

2019-05-05 07:21 UTC, ldealmei commented on Week1/exercise/w1/index.js
> +    const todoInput = document.getElementById("todoInput");
Idem, try selecting elements outside of the function, so that you don't select multiple times the same element

2019-05-05 07:31 UTC, bitsagarob approved these changes
great job, try to implement the remarks though

2019-05-10 20:18 UTC, yousefnk commented
week 2 - Yousef

2019-05-25 21:56 UTC, yousefnk commented
week 3

2019-07-06 11:09 UTC, closed without merging